services:
  web:
    build: .
    container_name: spineup
    env_file:
      - .env
    command: >
      sh -c "
      python3 manage.py makemigrations --noinput &&
      python3 manage.py migrate --noinput &&
      python3 manage.py collectstatic --noinput &&
      python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - "./src:/app"
    depends_on:
      - db
      - clamav

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_spineup:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TIME_ZONE: ${TIME_ZONE}
      USE_TZ: ${USE_TZ}

  clamav:
    image: mkodockx/docker-clamav:alpine   # Use a pre-built ClamAV container
    container_name: clamav
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/var/lib/clamav

volumes:
    postgres_data_spineup:
    clamav_data:
      