name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_EC2_SSH_KEY }}

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-54-208-224-53.compute-1.amazonaws.com << 'EOF'
            cd /home/ubuntu/spine-up
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            exit
          EOF
